<?xml version="1.0" encoding="utf-8"?><Database Class="BlogDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="Posts">
    <Type Name="Post">
      <Column Name="Id" AutoSync="Never" Type="System.Int32" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" CanBeNull="false" />
      <Column Name="Content" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>